### ISSUE TITLE
Custom style support (basics)

### ISSUE THREAD

**Issue by rsimon** [recogito/annotorious-3#3]
For reference: Luna Imaging currently uses the following custom styles:

```css
/** Hides the outer shapes - for this style we only need one **/
svg.a9s-annotationlayer .a9s-selection .a9s-outer, 
svg.a9s-annotationlayer .a9s-annotation .a9s-outer {
   display:none;
}

svg.a9s-annotationlayer .a9s-handle .a9s-handle-outer {
   display:none;
}

/** New style for the annotation outlines **/
svg.a9s-annotationlayer .a9s-selection .a9s-inner,
svg.a9s-annotationlayer .a9s-annotation .a9s-inner  {
   /*stroke-width:4;*/
   stroke:red;
   /*stroke-dasharray:5;*/
}

/** Disable the hover effect from the default stylesheet **/
svg.a9s-annotationlayer .a9s-annotation.editable:hover .a9s-inner {
   fill:transparent;
}

/** Corner handles **/
svg.a9s-annotationlayer .a9s-handle .a9s-handle-inner {
   fill:white;
   stroke:white;
}

/** Enable the dim mask, black with 60% transparency **/
svg.a9s-annotationlayer .a9s-selection-mask {
   fill:rgba(0, 0, 0, 0.6);
}

/** special effects **/
.openseadragon-canvas svg.a9s-annotationlayer .a9s-selection .a9s-inner,
.openseadragon-canvas svg.a9s-annotationlayer .a9s-annotation .a9s-inner  {
   stroke-dasharray: 1000;
   stroke-dashoffset: 1000;
   animation: dash 5s linear forwards;
}

@keyframes dash {
   to {
      stroke-dashoffset: 0;
   }
}
```
